# Generated by Django 3.0.1 on 2019-12-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('visitors', models.IntegerField()),
                ('create_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=1)),
            ],
        ),
    ]
