# Generated by Django 3.0.1 on 2019-12-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('visitors', models.IntegerField()),
                ('create_time', models.DateField()),
                ('update_time', models.DateField()),
                ('status', models.BooleanField()),
            ],
        ),
    ]
