# Generated by Django 3.0.1 on 2019-12-20 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='status',
            field=models.BooleanField(),
        ),
    ]
