# Generated by Django 3.0.1 on 2019-12-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('context', models.TextField(max_length=5000)),
                ('classify', models.IntegerField()),
                ('is_recommend', models.BooleanField()),
                ('id_top', models.BooleanField()),
                ('is_publish', models.BooleanField()),
                ('create_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Classify',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('superior', models.IntegerField()),
                ('describe', models.CharField(max_length=255)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=1)),
            ],
        ),
    ]
