# Generated by Django 3.0.1 on 2020-01-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(max_length=5000)),
                ('college', models.IntegerField(blank=True)),
                ('classify', models.IntegerField()),
                ('img_url', models.CharField(blank=True, max_length=255)),
                ('page_view', models.IntegerField(default=0)),
                ('is_recommend', models.BooleanField(default=0)),
                ('is_top', models.BooleanField(default=0)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Classify',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('describe', models.CharField(max_length=255)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=1)),
            ],
        ),
    ]
